//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP2010.Manage.FileTypes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SPManageFileTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SPManageFileTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SP2010.Manage.FileTypes.Resources.SPManageFileTypes", typeof(SPManageFileTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management upload file sizes.
        /// </summary>
        internal static string CustomAction_Title {
            get {
                return ResourceManager.GetString("CustomAction_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you can&apos;t upload the file, because &lt;i&gt;&lt;b&gt;{file}&lt;/b&gt;&lt;/i&gt; has upload size equels {size} Bytes, maximum upload size equels &lt;b&gt;{limitsize}&lt;/b&gt; Bytes.
        /// </summary>
        internal static string DownloadPage_Message {
            get {
                return ResourceManager.GetString("DownloadPage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        internal static string DownloadPage_PageTitle {
            get {
                return ResourceManager.GetString("DownloadPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        internal static string DownloadPage_PageTitleInTitleArea {
            get {
                return ResourceManager.GetString("DownloadPage_PageTitleInTitleArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature allows to manage uploading  file size for individual extensions on sharepoint web site.  Created by Smart84 (http://www.codeplex.com/site/users/view/smart84).
        /// </summary>
        internal static string Feature_Description {
            get {
                return ResourceManager.GetString("Feature_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage uploading file size (extensions).
        /// </summary>
        internal static string Feature_Name {
            get {
                return ResourceManager.GetString("Feature_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active (use).
        /// </summary>
        internal static string SettingPage_Active {
            get {
                return ResourceManager.GetString("SettingPage_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new file extension.
        /// </summary>
        internal static string SettingPage_AddNewType {
            get {
                return ResourceManager.GetString("SettingPage_AddNewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return confirm(&apos;Are you sure?&apos;);.
        /// </summary>
        internal static string SettingPage_AddNewType_Confirm {
            get {
                return ResourceManager.GetString("SettingPage_AddNewType_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove?.
        /// </summary>
        internal static string SettingPage_Delete {
            get {
                return ResourceManager.GetString("SettingPage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data couldn&apos;t saved.
        /// </summary>
        internal static string SettingPage_Failed {
            get {
                return ResourceManager.GetString("SettingPage_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension (i.e: .txt).
        /// </summary>
        internal static string SettingPage_FileType {
            get {
                return ResourceManager.GetString("SettingPage_FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no items to show in this view..
        /// </summary>
        internal static string SettingPage_Grid_NoItems {
            get {
                return ResourceManager.GetString("SettingPage_Grid_NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension &lt;b&gt;{0}&lt;/b&gt; already has been added..
        /// </summary>
        internal static string SettingPage_IsExists {
            get {
                return ResourceManager.GetString("SettingPage_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum upload size of file (bytes).
        /// </summary>
        internal static string SettingPage_MaxSize {
            get {
                return ResourceManager.GetString("SettingPage_MaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management upload size files.
        /// </summary>
        internal static string SettingPage_PageTitle {
            get {
                return ResourceManager.GetString("SettingPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management upload size files.
        /// </summary>
        internal static string SettingPage_PageTitleInTitleArea {
            get {
                return ResourceManager.GetString("SettingPage_PageTitleInTitleArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        internal static string SettingPage_SaveSettings {
            get {
                return ResourceManager.GetString("SettingPage_SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return confirm(&apos;Are you sure?&apos;);.
        /// </summary>
        internal static string SettingPage_SaveSettings_Confirm {
            get {
                return ResourceManager.GetString("SettingPage_SaveSettings_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data have been saved.
        /// </summary>
        internal static string SettingPage_Success {
            get {
                return ResourceManager.GetString("SettingPage_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow manage uploading maximum size files for site collection..
        /// </summary>
        internal static string SettingPage_TemplateDescription {
            get {
                return ResourceManager.GetString("SettingPage_TemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading management .
        /// </summary>
        internal static string SettingPage_TemplateTitle {
            get {
                return ResourceManager.GetString("SettingPage_TemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should be great than 0.
        /// </summary>
        internal static string SettingPage_Validator_RangeSize {
            get {
                return ResourceManager.GetString("SettingPage_Validator_RangeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill use sample: .txt.
        /// </summary>
        internal static string SettingPage_Validator_RegExtension {
            get {
                return ResourceManager.GetString("SettingPage_Validator_RegExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requiered field.
        /// </summary>
        internal static string SettingPage_Validator_ReqExtension {
            get {
                return ResourceManager.GetString("SettingPage_Validator_ReqExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requiered field.
        /// </summary>
        internal static string SettingPage_Validator_ReqSize {
            get {
                return ResourceManager.GetString("SettingPage_Validator_ReqSize", resourceCulture);
            }
        }
    }
}
